server:
  port: 12990

spring:
  .profiles:
    active: test
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
        ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
   ## 静态资源映射
  resources:
    static-locations: classpath:/static/,classpath:/views/

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml

jwt:
  # 加密秘钥
  secret: f4e2e52034348f86b67cde581c0f9eb5
  # token有效时长，7天，单位秒
  expire: 604800
  header: token

